In [23]:
import pandas as pd # veri analizi ve veri işleme için kullanılır (dataFrame yapısı sağlar)
from sklearn.feature_extraction.text import CountVectorizer # metinleri sayısal forma dönüştürür (BoW yöntemi)
import re #metinlerde temizleme işlemi yapar

In [24]:
import kagglehub
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.


In [25]:
veri = pd.read_csv(f"{path}/IMDB Dataset.csv")
veri.head()

yorumlar=veri["review"]
etiketler=veri["sentiment"]

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words=set(stopwords.words("english"))

#metin temizleme
def metin_temizle(metin):
  metin=metin.lower() #küçük harfe çevir
  metin= re.sub(r"\d+","",metin) #rakamları kaldır
  metin=re.sub(r"[^\w\s]","",metin) # özel karakterleri kaldır
  metin=" ".join([kelime for kelime in metin.split() if len(kelime) > 2 and kelime not in stop_words]) #kısa kelimeleri 2 harften kısa olanları kaldır
  return metin

temizlenmis_yorumlar=[metin_temizle(y) for y in yorumlar]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [26]:
#BoW
bow_modeli=CountVectorizer()

yorum_vektorleri=bow_modeli.fit_transform(temizlenmis_yorumlar[:75]) #ilk 75 yorum

kelime_kumesi=bow_modeli.get_feature_names_out() #vocabulary (kelime kümesi)

vektor_temsili=yorum_vektorleri.toarray()
print(f"Vektör temlisi: {vektor_temsili}")

Vektör temlisi: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
df_bow=pd.DataFrame(vektor_temsili, columns=kelime_kumesi)
print(df_bow.head())

   abbot  abetted  abiding  ability  able  aboveaverage  abraham  abrahams  \
0      0        0        0        0     0             0        0         0   
1      0        0        0        0     0             0        0         0   
2      0        0        0        0     0             0        0         0   
3      0        0        0        0     0             0        0         0   
4      0        0        0        0     0             0        0         0   

   absolute  absolutely  ...  yuen  zack  zany  zellweger  zerog  zombie  \
0         0           0  ...     0     0     0          0      0       0   
1         0           0  ...     0     0     0          0      0       0   
2         0           0  ...     0     0     0          0      0       0   
3         0           0  ...     0     0     0          0      0       1   
4         0           0  ...     0     0     0          0      0       0   

   zombiebr  zone  zooms  zwick  
0         0     0      0      0  
1     

In [28]:
#kelime frekanslarını hesapla
from collections import Counter # elemanların frekansını sağlar (ör: kelime sıklığı hesaplama)
kelime_sayilari=yorum_vektorleri.sum(axis=0).A1 #her kelimenin toplam kaç adet geçtiğini bul
kelime_frekansi=dict(zip(kelime_kumesi,kelime_sayilari))
en_cok_gecen_5= Counter(kelime_frekansi).most_common(5)

print(f"En çok geçen 5 kelime: {en_cok_gecen_5}")


En çok geçen 5 kelime: [('movie', np.int64(123)), ('film', np.int64(98)), ('one', np.int64(72)), ('like', np.int64(59)), ('good', np.int64(38))]
